# fly.toml app configuration file generated for nwc-periodic-payments-db on 2023-05-22T13:41:36+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "nwc-periodic-payments-db"
primary_region = "lax"

[env]
  PRIMARY_REGION = "lax"

[[mounts]]
  source = "pg_data"
  destination = "/data"

[checks]
  [checks.pg]
    port = 5500
    type = "http"
    interval = "15s"
    timeout = "10s"
    path = "/flycheck/pg"
  [checks.role]
    port = 5500
    type = "http"
    interval = "15s"
    timeout = "10s"
    path = "/flycheck/role"
  [checks.vm]
    port = 5500
    type = "http"
    interval = "1m0s"
    timeout = "10s"
    path = "/flycheck/vm"

[metrics]
  port = 9187
  path = "/metrics"

[[services]]
  internal_port = 5432 # Postgres instance
  protocol = "tcp"

[[services.ports]]
  handlers = ["pg_tls"]
  port = 5432